"""Process the Shreve, Crump & Low mobile-app screenshots into the gallery shown
in the Work case-study modal. Same blur-up pipeline as process_media.py:
EXIF-upright -> downscale -> webp + jpg, plus a tiny base64 blur placeholder.

Output: public/media/scl/<stem>.webp (+ .jpg) and src/lib/galleryData.ts (the
generated source of truth the site imports). Run from the project root:

    python scripts/process_scl.py
"""
import base64, io, os

from PIL import Image, ImageOps

SRC = "Philfolio-images"
OUT = "public/media/scl"
TS_OUT = "src/lib/galleryData.ts"
CAP = 1200  # longest side; phone screens display ~560px tall, so this covers 2x
os.makedirs(OUT, exist_ok=True)

# ordered (source file, dest stem, caption) — the order is the gallery order.
JOBS = [
    ("scl3.jpeg", "scl-feed",      "New arrivals feed"),
    ("scl2.PNG",  "scl-patek-pc",  "Patek Philippe — Perpetual Calendar"),
    ("scl8.PNG",  "scl-lange",     "A. Lange & Söhne — Aventurine"),
    ("scl9.PNG",  "scl-aquanaut",  "Patek Philippe — Aquanaut"),
    ("scl7.PNG",  "scl-vacheron",  "Vacheron Constantin — Patrimony"),
    ("scl5.jpeg", "scl-ap",        "Audemars Piguet — Royal Oak"),
    ("scl6.PNG",  "scl-patek-ch",  "Patek Philippe — Chronograph"),
    ("scl0.png",  "scl-catalog",   "Catalog — browse & search"),
]


def blur_uri(img):
    t = img.copy().convert("RGB")
    t.thumbnail((20, 20))
    b = io.BytesIO()
    t.save(b, format="JPEG", quality=40)
    return "data:image/jpeg;base64," + base64.b64encode(b.getvalue()).decode()


shots = []
for src, stem, caption in JOBS:
    p = os.path.join(SRC, src)
    if not os.path.exists(p):
        print(f"MISSING {p}")
        continue
    img = Image.open(p)
    img = ImageOps.exif_transpose(img)  # bake EXIF rotation into pixels
    img = img.convert("RGB")
    w, h = img.size
    scale = min(1.0, CAP / max(w, h))
    if scale < 1.0:
        img = img.resize((round(w * scale), round(h * scale)), Image.LANCZOS)
    img.save(os.path.join(OUT, stem + ".webp"), format="WEBP", quality=82, method=6)
    img.save(os.path.join(OUT, stem + ".jpg"), format="JPEG", quality=84, optimize=True)
    shots.append((stem, caption, blur_uri(img), img.size))
    print(f"OK {src} -> {stem}  final={img.size}")

# Emit the generated TS the site imports. base64 blurs are huge, so keeping them
# out of the hand-edited content.ts keeps that file readable.
out = [
    "// AUTO-GENERATED by scripts/process_scl.py — do not edit by hand.",
    "// The Shreve, Crump & Low app gallery shown in the Work case-study modal.",
    "export type Shot = { src: string; blur: string; caption: string }",
    "",
    "export const sclGallery: Shot[] = [",
]
for stem, caption, blur, _size in shots:
    cap = caption.replace("\\", "\\\\").replace("'", "\\'")
    out.append("  {")
    out.append(f"    src: '/media/scl/{stem}.webp',")
    out.append(f"    blur: '{blur}',")
    out.append(f"    caption: '{cap}',")
    out.append("  },")
out.append("]")
out.append("")

with open(TS_OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(out))

print(f"WROTE {TS_OUT}  ({len(shots)} shots)")
